before_script:
  - export CI_BUILD_REF_NAME_NORMALIZED=$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export CI_APP_VOLUME=${CI_PROJECT_DIR}
  - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}${CI_BUILD_REF_NAME_NORMALIZED}
  - mv tests/docker-compose.ci.override.yml tests/docker-compose.override.yml
  - cd tests
  - sh ./env.sh

build:
  stage: build
  script:
    - export GIIANT_TEST_DB=sakila
    - sh init.sh

test:
  stage: test
  script:
    - export GIIANT_TEST_DB=sakila
    - sh run.sh
  artifacts:
    paths:
      - tests/_output

cleanup:
  stage: deploy
  when: always
  script:
    - docker-compose --x-networking kill
    - docker-compose --x-networking rm -fv
    - docker network rm $COMPOSE_PROJECT_NAME
