before_script:
  - export CI_BUILD_REF_NAME_NORMALIZED=$(echo ${CI_BUILD_REF_NAME} | tr -dc '[:alnum:]\n\r' | tr '[:upper:]' '[:lower:]')
  - export CI_APP_VOLUME=${CI_PROJECT_DIR}
  - export COMPOSE_PROJECT_NAME=buildref${CI_BUILD_REF}${CI_BUILD_REF_NAME_NORMALIZED}
  - mv tests/docker-compose.ci.override.yml tests/docker-compose.override.yml
  - cd tests
  - docker --version
  - docker-compose --version
  - sh ./env.sh

stages:
  - build
  - test
  - cleanup

1-build:
  stage: build
  script:
    - export GIIANT_TEST_DB=sakila
    - sh init.sh

2-test:
  stage: test
  script:
    - export GIIANT_TEST_DB=sakila
    - sh run.sh
  artifacts:
    paths:
      - tests/_output

3-cleanup:
  stage: cleanup
  when: always
  script:
    - docker-compose kill
    - docker-compose rm -fv

