sudo: required

language: php

services:
  - docker

before_install:
  - cd tests
  - docker-compose build --pull

script:
  - docker-compose run --rm phpfpm yii app/setup
  - make all
  - make test

